version: '3.1'

services:
    server:
        image: node:14-alpine
        env_file: .env
        working_dir: /app
        command: sh -c "npm i && npm run dev"
        volumes:
            - ./:/app
        ports:
            - 3000:3000

    mongo:
        image: mongo
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}
            MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}

    mongo-express:
        image: mongo-express
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USER}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASSWORD}
