version: '3.1'

services:
    server:
        command: sh -c "npm i && npm run dev"
        ports:
            - 3000:3000

    mongo-express:
        image: mongo-express
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USER}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASSWORD}
