version: '3.1'

services:
    server:
        image: node:14-alpine
        env_file: .env
        working_dir: /app
        volumes:
            - ./:/app

    mongo:
        image: mongo
        environment:
            MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}
            MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
